root = "/app"
tmp_dir = "/tmp"

[build]
pre_cmd = []
cmd = "go build -o /tmp/main main.go"
entrypoint = ["/tmp/main"]
include_ext = ["go", "templ", "sql"]
exclude_regex = ["_templ\\.go"]
exclude_dir = []
